# NumPy
https://numpy.org/

In [4]:
import numpy as np
np.__version__

'1.24.3'

### Criando arrays Numpy

In [5]:
arr1 = np.array([8, 12, 18, 26, 29, 30])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(6,)

Um array NumPy, parte da biblioteca NumPy em Python, é uma estrutura de dados que representa uma grade de valores, todos do mesmo tipo. Esses arrays são eficientes para manipulação de dados numéricos, oferecendo operações otimizadas e suporte para cálculos vetorizados. Em comparação com listas Python, os arrays NumPy são homogêneos, significando que todos os elementos devem ter o mesmo tipo de dado. Eles são amplamente utilizados em computação científica, análise de dados e aprendizado de máquina, oferecendo desempenho superior em operações numéricas e funcionalidades específicas para tais tarefas.

### Indexação de arrays NumPy

In [10]:
# Cria uma lista com os valores ímpares de 1 a 5
indices = [x for x in range(1, 6, 2)]

In [11]:
# Retorna os itens do array NumPy, correspondentes aos valores de uma lista passada como parâmetro
arr1[indices]

array([12, 26, 30])

In [22]:
# Retorna um array booleano, correspondente aos números pares do array usado de parâmetro
mask = (arr1 % 2 == 0)
print(arr1)
print(mask)

[ 8 12 18 26 29 30]
[ True  True  True  True False  True]


In [24]:
# Retorno apenas os valores pares do array
arr1[mask]

array([ 8, 12, 18, 26, 30])

### Funções NumPy

In [25]:
arr2 = np.array([1, 3, 5, 7, 9])

In [37]:
# Retorna a soma cumulativa dos elementos do array
arr2.cumsum()

array([ 1,  4,  9, 16, 25])

In [38]:
# Retorna o produto cumulativa dos elementos do array
arr2.cumprod()

array([  1,   3,  15, 105, 945])

In [35]:
arr3 = np.arange(0, 250, 20)

In [36]:
arr3

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240])

In [39]:
arr3.dtype

dtype('int64')

In [41]:
arr4 = np.zeros(8)

In [42]:
arr4

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
arr5 = np.eye(5)

In [44]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])